/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dog.drc.glb --draco --debug 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/dog.drc.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="camera1_group" scale={0.01}>
            <group name="camera1_aim" position={[-13.972, 9.088, -19.211]} rotation={[0, 0.281, 0]} />
          </group>
          <group name="DOGSTUDIO_RIGDOGSTUDIO_RIG" scale={0.01}>
            <group name="DOGSTUDIO_RIGDOG_MESH">
              <skinnedMesh name="DOGSTUDIO_RIGDOG_BODY_msh" geometry={nodes.DOGSTUDIO_RIGDOG_BODY_msh.geometry} material={materials.dog} skeleton={nodes.DOGSTUDIO_RIGDOG_BODY_msh.skeleton} />
            </group>
            <group name="DOGSTUDIO_RIGDOG_JNT">
              <primitive object={nodes.DOGSTUDIO_RIGJNT_chest} />
            </group>
          </group>
          <group name="BRANCHS_RIG_01BRANCHS_MSH" scale={0.01}>
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_1" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_1.geometry} material={materials.leafs} position={[-16.757, -12.64, -28.838]} rotation={[1.782, 0.266, 3.089]} scale={1.153} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_2" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_2.geometry} material={materials.leafs} position={[14.925, 9.954, -9.987]} rotation={[1.145, -0.284, -0.057]} scale={1.531} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_3" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_3.geometry} material={materials.leafs} position={[8.051, 20.932, 2.92]} rotation={[-2.63, -0.193, 0.407]} scale={1.265} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_4" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_4.geometry} material={materials.leafs} position={[-34.073, -0.382, -53.425]} rotation={[0.179, -0.283, 0.965]} scale={1.134} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_5" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_5.geometry} material={materials.leafs} position={[-14.69, -5.988, -15.603]} rotation={[0.844, 0.117, -0.191]} scale={1.319} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_6" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_6.geometry} material={materials.leafs} position={[-39.04, 43.646, -34.537]} rotation={[-2.003, -0.347, -2.179]} scale={1.362} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_7" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_7.geometry} material={materials.leafs} position={[-39.47, 48.375, -49.793]} rotation={[0.58, -0.69, -0.213]} scale={1.05} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_8" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_8.geometry} material={materials.leafs} position={[-1.621, -6.875, -53.134]} rotation={[-1.072, 0.092, -2.898]} scale={2.31} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_9" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_9.geometry} material={materials.leafs} position={[-26.612, 2.448, -11.348]} rotation={[-2.021, -0.869, -2.323]} scale={1.176} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_10" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_10.geometry} material={materials.leafs} position={[-21.698, 60.318, -42.039]} rotation={[0.095, -0.085, -0.812]} scale={1.452} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_branch_11" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_branch_11.geometry} material={materials.leafs} position={[12.833, 50.17, 5.529]} rotation={[-0.417, -1.095, -0.824]} scale={1.105} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_01" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_01.geometry} material={materials.leafs} position={[6.63, 100.14, 2.126]} rotation={[-2.616, 0.779, 2.704]} scale={4.79} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_02" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_02.geometry} material={materials.leafs} position={[14.13, 71.39, 15.606]} rotation={[-1.882, 1.09, 2.278]} scale={4.389} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_03" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_03.geometry} material={materials.leafs} position={[6.523, 107.99, -3.479]} rotation={[2.056, -1.46, 1.809]} scale={4.389} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_04" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_04.geometry} material={materials.leafs} position={[-43.177, 41.824, -60.821]} rotation={[-0.936, -1.218, -0.904]} scale={3.422} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_05" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_hazel_leaf_05.geometry} material={materials.leafs} position={[-43.251, 4.629, -67.259]} rotation={[-2.332, 1.066, 1.325]} scale={4.389} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_01" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_01.geometry} material={materials.leafs} position={[-4.041, 74.123, -33.488]} rotation={[0.663, -0.415, -0.787]} scale={6.458} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_02" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_02.geometry} material={materials.leafs} position={[-54.661, 30.267, -29.16]} rotation={[0.754, 0.074, -0.794]} scale={3.694} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_03" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_03.geometry} material={materials.leafs} position={[19.11, 48.771, -5.125]} rotation={[-1.851, 1, 0.715]} scale={6.938} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_04" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_04.geometry} material={materials.leafs} position={[1.505, 24.765, -11.724]} rotation={[0.173, -0.69, 0.025]} scale={6.938} />
            <mesh name="BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_05" geometry={nodes.BRANCHS_RIG_01BRANCHS_MSH_maple_leaf_05.geometry} material={materials.leafs} position={[-47.338, 18.599, -65.942]} rotation={[0, -0.191, 0.282]} scale={6.938} />
          </group>
          <group name="BRANCHS_RIG_02BRANCHS_MSH" scale={0.01}>
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_branch_6" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_branch_6.geometry} material={materials.leafs} position={[-4.343, 28.526, -32.722]} rotation={[0.722, -0.055, 3.008]} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_01" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_01.geometry} material={materials.leafs} position={[6.453, 96.151, 9.401]} rotation={[0.194, -0.093, 1.187]} scale={3.419} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_02" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_02.geometry} material={materials.leafs} position={[-0.185, 83.782, -23.893]} rotation={[0.389, 0.142, 1.006]} scale={2.924} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_03" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_03.geometry} material={materials.leafs} position={[20.863, 52.278, -29.572]} rotation={[1.493, 1.016, -2.968]} scale={3.87} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_04" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_04.geometry} material={materials.leafs} position={[-53.669, 18.069, -61.542]} rotation={[0.649, -0.528, 1.748]} scale={3.017} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_05" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_hazel_leaf_05.geometry} material={materials.leafs} position={[21.871, 50.508, -25.345]} rotation={[1.322, 0.295, -2.427]} scale={2.597} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_01" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_01.geometry} material={materials.leafs} position={[-58.717, 30.183, -46.328]} rotation={[-2.741, -0.292, 0.831]} scale={4.921} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_02" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_02.geometry} material={materials.leafs} position={[-41.818, 5.712, -52.802]} rotation={[0, -0.323, 0]} scale={6.117} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_03" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_03.geometry} material={materials.leafs} position={[-4.153, 114.756, -7.1]} rotation={[0.453, -1.157, 0]} scale={3.898} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_04" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_04.geometry} material={materials.leafs} position={[15.658, 82.56, 11.765]} rotation={[-2.906, 0.272, 3.11]} scale={4.604} />
            <mesh name="BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_05" geometry={nodes.BRANCHS_RIG_02BRANCHS_MSH_maple_leaf_05.geometry} material={materials.leafs} position={[21.932, 55.104, -15.58]} rotation={[2.116, 0.822, 2.786]} scale={6.117} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog.drc.glb')
